// Generated by scripts/build-lens.mjs — do not edit.

// ===== zh (extension) =====
(function () {
'use strict';

const ZHX_HAN_RE = /[㐀-䶿一-鿿豈-﫿]/;
const ZHX_HAN_RUN = /[㐀-䶿一-鿿豈-﫿]+/g;

const ZHX_TONE_MARKS = {
  a: 'āáǎà', e: 'ēéěè', i: 'īíǐì', o: 'ōóǒò', u: 'ūúǔù', 'ü': 'ǖǘǚǜ',
  A: 'ĀÁǍÀ', E: 'ĒÉĚÈ', I: 'ĪÍǏÌ', O: 'ŌÓǑÒ', U: 'ŪÚǓÙ', 'Ü': 'ǕǗǙǛ',
};

function zhxAccentSyllable(syl) {
  const m = syl.match(/^([A-Za-zü:]+)([1-5])$/);
  if (!m) return syl.replace(/u:/g, 'ü').replace(/U:/g, 'Ü');
  let [, body, tone] = m;
  body = body.replace(/u:/g, 'ü').replace(/U:/g, 'Ü');
  tone = Number(tone);
  if (tone === 5) return body;
  const lower = body.toLowerCase();
  let idx = lower.indexOf('a');
  if (idx < 0) idx = lower.indexOf('e');
  if (idx < 0) idx = lower.indexOf('ou');
  if (idx < 0) {
    for (let i = lower.length - 1; i >= 0; i--) {
      if ('iouü'.includes(lower[i])) { idx = i; break; }
    }
  }
  if (idx < 0) return body;
  const marked = ZHX_TONE_MARKS[body[idx]];
  if (!marked) return body;
  return body.slice(0, idx) + marked[tone - 1] + body.slice(idx + 1);
}

function zhxAccent(pinyin) {
  return pinyin.split(' ').map(zhxAccentSyllable).join(' ');
}

// 一/不 tone sandhi (display-only, the first pronunciation rule beginners learn):
// 不 bù → bú before a 4th tone; 一 yī → yí before 4th, → yì before 1st/2nd/3rd.
// Only applies when a following syllable exists (so ordinals 第一 and final 统一 stay yī).
function zhxSandhi(numbered) {
  const syls = numbered.split(' ');
  const toneOf = (s) => (s.match(/([1-5])(?:[a-z])?$/i) || [])[1];
  for (let i = 0; i < syls.length - 1; i++) {
    const m = syls[i].match(/^([a-zü:]+?)([1-5])$/i);
    if (!m) continue;
    const base = m[1].toLowerCase();
    const nt = toneOf(syls[i + 1]);
    if (!nt) continue;
    if (base === 'bu' && m[2] === '4' && nt === '4') syls[i] = m[1] + '2';
    else if (base === 'yi' && m[2] === '1') {
      if (nt === '4') syls[i] = m[1] + '2';
      else if (nt === '1' || nt === '2' || nt === '3') syls[i] = m[1] + '4';
    }
  }
  return syls.join(' ');
}

// CEDICT stores erhua as a separate "r5" syllable; fuse the trailing r onto the
// previous syllable so 一点儿 reads "yì diǎnr", not "yì diǎn r".
function zhxMandarin(numbered) {
  return zhxAccent(zhxSandhi(numbered)).replace(/ r(?=\s|$)/g, 'r');
}

let zhxIndex = null;
let zhxMaxLen = 1;
let zhxDictPromise = null;
let zhxHsk = null;
let zhxSentPromise = null;
let zhxReadings = {};

const ZHX_READING_SLOT = { yue: 0, nan: 1, teo: 2 };

function zhxReadingFor(mode, numberedPinyin, ...wordForms) {
  const fallback = numberedPinyin ? zhxMandarin(numberedPinyin) : null;
  const slot = ZHX_READING_SLOT[mode];
  if (slot === undefined) return fallback;
  for (const w of wordForms) {
    const direct = w && zhxReadings[w]?.[slot];
    if (direct) return direct;
  }
  const word = wordForms.find(Boolean);
  if (word && word.length > 1) {
    const parts = [];
    for (const ch of word) {
      const r = zhxReadings[ch]?.[slot];
      if (!r) return fallback;
      parts.push(r.split(/[,;/]/)[0].trim());
    }
    return parts.join(' ');
  }
  return fallback;
}

function zhxEnsureDict() {
  zhxDictPromise ??= (async () => {
    const [res, hskRes, readRes, cantoRes] = await Promise.all([
      fetch(chrome.runtime.getURL('dict/zh/cedict.json')),
      fetch(chrome.runtime.getURL('dict/zh/hsk.json')).catch(() => null),
      fetch(chrome.runtime.getURL('dict/zh/readings.json')).catch(() => null),
      fetch(chrome.runtime.getURL('dict/zh/canto.json')).catch(() => null),
    ]);
    zhxHsk = hskRes && hskRes.ok ? await hskRes.json() : {};
    zhxReadings = readRes && readRes.ok ? await readRes.json() : {};
    const cantoRows = cantoRes && cantoRes.ok ? await cantoRes.json() : [];
    const rows = (await res.json()).concat(cantoRows);
    zhxIndex = new Map();
    const add = (key, entry) => {
      const list = zhxIndex.get(key);
      if (list) list.push(entry); else zhxIndex.set(key, [entry]);
    };
    for (const [s, t, p, d] of rows) {
      const entry = { s, t, p, d };
      add(s, entry);
      if (t !== s) add(t, entry);
      if (s.length > zhxMaxLen) zhxMaxLen = s.length;
    }
    zhxMaxLen = Math.min(zhxMaxLen, 12);
  })();
  return zhxDictPromise;
}

// Most-frequent reading for common polyphones (多音字) and a few multi-char words
// that CEDICT lists in a misleading order. Consulted when a word/char has several
// entries and greedy "first entry wins" would pick a rarer reading. Values are
// CEDICT numbered pinyin, lowercased. This can't be context-perfect (single-char
// readings are context-dependent) but the most-frequent reading is the best default.
const ZHX_PRIORITY = {
  行: 'xing2', 重: 'zhong4', 还: 'hai2', 差: 'cha4', 都: 'dou1', 长: 'chang2',
  中: 'zhong1', 教: 'jiao1', 好: 'hao3', 了: 'le5', 着: 'zhe5', 得: 'de5',
  地: 'de5', 会: 'hui4', 为: 'wei4', 要: 'yao4', 少: 'shao3', 发: 'fa1',
  吗: 'ma5', 呢: 'ne5', 吧: 'ba5', 啊: 'a5', 曾: 'ceng2', 应: 'ying1',
  更: 'geng4', 兴: 'xing4', 空: 'kong1', 觉: 'jue2', 只: 'zhi3', 种: 'zhong3',
  东西: 'dong1 xi5', 花儿: 'hua1 r5', 大夫: 'dai4 fu5', 人家: 'ren2 jia5',
};

// Extract measure words (量词) from CEDICT's "CL:個|个[ge4],位[wei4]" gloss lines
// and surface them as a distinct field so the popup can badge them for learners.
function zhxClassifiers(entries) {
  for (const e of entries) {
    for (const d of e.d) {
      const m = d.match(/^CL:(.+)$/);
      if (!m) continue;
      const cls = m[1].split(',').map((c) => {
        const simp = c.split('|').pop();          // prefer simplified after |
        return simp.replace(/\[[^\]]*\]/g, '').trim();
      }).filter(Boolean);
      if (cls.length) return cls;
    }
  }
  return undefined;
}

function zhxPickEntry(word, entries) {
  const pref = ZHX_PRIORITY[word];
  if (pref) {
    const hit = entries.find((e) => e.p.toLowerCase() === pref);
    if (hit) return hit;
  }
  return entries.find((e) => !/^[A-Z]/.test(e.p)) ?? entries[0];
}

// Word families: given a character, the common multi-character words built from it.
// Characters are meaning-atoms in Chinese, so the family around 电 (电话/电脑/电视)
// is how vocabulary actually clusters. Built lazily once; ranked HSK-first.
let zhxCharWords = null;
const ZHX_HAN_ONLY = /^[㐀-䶿一-鿿々]+$/;

function zhxBuildCharIndex() {
  if (zhxCharWords) return;
  zhxCharWords = new Map();
  for (const word of zhxIndex.keys()) {
    if (word.length < 2 || word.length > 4 || !ZHX_HAN_ONLY.test(word)) continue;
    for (const ch of new Set(word)) {
      let list = zhxCharWords.get(ch);
      if (!list) { list = []; zhxCharWords.set(ch, list); }
      list.push(word);
    }
  }
}

function zhxFamily(ch, exclude, mode, limit) {
  zhxBuildCharIndex();
  const words = [...new Set(zhxCharWords.get(ch) ?? [])]
    .filter((w) => w !== exclude)
    .sort((a, b) => (zhxHsk[a] ?? 99) - (zhxHsk[b] ?? 99) || a.length - b.length)
    .slice(0, limit ?? 10);
  return words.map((w) => {
    const entry = zhxPickEntry(w, zhxIndex.get(w));
    const gloss = entry.d.find((d) => !/^CL:/.test(d)) ?? entry.d[0] ?? '';
    return { w, p: zhxReadingFor(mode, entry.p, w, entry.s, entry.t), g: gloss, h: zhxHsk[w] ?? 0 };
  });
}

function zhxSegmentRun(run, mode) {
  const tokens = [];
  let i = 0;
  while (i < run.length) {
    let word = null;
    for (let len = Math.min(zhxMaxLen, run.length - i); len >= 1; len--) {
      const cand = run.slice(i, i + len);
      if (zhxIndex.has(cand)) { word = cand; break; }
    }
    if (!word) {
      tokens.push({ w: run[i], p: zhxReadingFor(mode, null, run[i]), han: true, h: zhxHsk[run[i]] ?? 0 });
      i += 1;
    } else {
      const entries = zhxIndex.get(word);
      const entry = zhxPickEntry(word, entries);
      tokens.push({ w: word, p: zhxReadingFor(mode, entry.p, word, entry.s, entry.t), han: true, h: zhxHsk[word] ?? 0 });
      i += word.length;
    }
  }
  return tokens;
}

function zhxTokenize(text, mode) {
  const tokens = [];
  let last = 0;
  for (const m of text.matchAll(ZHX_HAN_RUN)) {
    if (m.index > last) tokens.push({ w: text.slice(last, m.index), p: null, han: false });
    tokens.push(...zhxSegmentRun(m[0], mode));
    last = m.index + m[0].length;
  }
  if (last < text.length) tokens.push({ w: text.slice(last), p: null, han: false });
  return tokens;
}

function zhxCharBreakdown(word, wordPinyin, mode) {
  const syls = wordPinyin ? wordPinyin.split(' ') : [];
  return [...word].map((ch, i) => {
    const entries = zhxIndex.get(ch);
    if (!entries) return { ch, p: zhxReadingFor(mode, null, ch), gloss: null };
    const target = syls[i] ? syls[i].toLowerCase() : null;
    const candidates = target ? entries.filter((e) => e.p.toLowerCase() === target) : [];
    const match = candidates.find((e) => !/^[A-Z]/.test(e.p))
      ?? candidates[0]
      ?? entries.find((e) => !/^[A-Z]/.test(e.p))
      ?? entries[0];
    const gloss = match.d.find((def) => !/^variant of|^see |^surname /i.test(def)) ?? match.d[0];
    return { ch, p: zhxReadingFor(mode, match.p, ch), gloss };
  });
}

// Curated "literally A + B" breakdowns. Hand-picked, because decomposition can lie:
// 东西 is not "east-west" and 马虎 is not a zoo. Entries are [breakdown, note?] where the
// note flags idiomatic drift, phonetic loans, honorifics — anything where the parts don't
// honestly sum to the meaning. Keys are simplified; lookup also tries the entry's s-form
// so traditional selections (電腦) resolve too. No entry -> no line shown: silence over lies.
const ZHX_LITERAL = {
  // transparent compounds — the parts genuinely build the meaning
  电脑: ['电 electric + 脑 brain'],
  电话: ['电 electric + 话 speech'],
  电影: ['电 electric + 影 shadow'],
  电视: ['电 electric + 视 vision'],
  电池: ['电 electric + 池 pool'],
  电梯: ['电 electric + 梯 ladder'],
  手机: ['手 hand + 机 machine'],
  飞机: ['飞 fly + 机 machine'],
  火车: ['火 fire + 车 vehicle'],
  汽车: ['汽 vapour + 车 vehicle'],
  火山: ['火 fire + 山 mountain'],
  火锅: ['火 fire + 锅 pot'],
  水果: ['水 water + 果 fruit'],
  牛奶: ['牛 cow + 奶 milk'],
  地铁: ['地 ground + 铁 iron'],
  地图: ['地 earth + 图 chart'],
  明天: ['明 next/bright + 天 day'],
  今天: ['今 present + 天 day'],
  昨天: ['昨 past + 天 day'],
  天气: ['天 sky + 气 air/qi'],
  空气: ['空 empty + 气 air'],
  大学: ['大 great + 学 learning'],
  中学: ['中 middle + 学 learning'],
  小学: ['小 small + 学 learning'],
  学校: ['学 study + 校 school-grounds'],
  学生: ['学 study + 生 person'],
  学习: ['学 study + 习 practise'],
  中文: ['中 China + 文 writing'],
  汉字: ['汉 Han + 字 character'],
  名字: ['名 name + 字 given name'],
  词典: ['词 word + 典 canon'],
  图书馆: ['图 chart + 书 book + 馆 hall'],
  动物: ['动 moving + 物 thing'],
  植物: ['植 planted + 物 thing'],
  熊猫: ['熊 bear + 猫 cat'],
  眼镜: ['眼 eye + 镜 lens'],
  手表: ['手 hand + 表 gauge'],
  冰箱: ['冰 ice + 箱 chest'],
  洗手间: ['洗 wash + 手 hand + 间 room'],
  自行车: ['自 self + 行 travel + 车 vehicle'],
  出租车: ['出租 rent out + 车 vehicle'],
  长城: ['长 long + 城 wall'],
  生日: ['生 birth + 日 day'],
  时间: ['时 time + 间 interval'],
  房间: ['房 house + 间 chamber'],
  问题: ['问 ask + 题 topic'],
  帮助: ['帮 assist + 助 aid'],
  工作: ['工 work + 作 do'],
  好吃: ['好 good + 吃 to eat'],
  好看: ['好 good + 看 to look at'],
  面包: ['面 flour + 包 bundle'],
  故事: ['故 past + 事 matter'],
  网站: ['网 net + 站 station'],
  网络: ['网 net + 络 mesh'],
  外国: ['外 outside + 国 country'],
  中国: ['中 middle + 国 kingdom', 'historically “the Middle Kingdom”'],
  世界: ['世 generations + 界 boundaries', 'from Buddhist usage: all of time and space'],
  // prefixes, honorifics, grammaticalized forms — parts need a caveat
  老师: ['老 venerable + 师 master', '老 is a respectful prefix here, not “old”'],
  先生: ['先 before + 生 born', 'honorific: “one born before me” → Mr, sir'],
  太太: ['太 great + 太 great', 'honorific reduplication → Mrs, wife'],
  美国: ['美 beautiful + 国 country', '美 is phonetic, from 亚美利加 “America”'],
  英国: ['英 outstanding + 国 country', '英 is phonetic, from 英吉利 “England”'],
  法国: ['法 law + 国 country', '法 is phonetic, from 法兰西 “France”'],
  // idiomatic — the meaning is NOT the sum of the parts
  东西: ['东 east + 西 west', 'idiomatic: “things” — the parts don’t add up'],
  马虎: ['马 horse + 虎 tiger', 'idiomatic: “careless” — from a folk tale, not the animals'],
  马上: ['马 horse + 上 on', 'idiomatic: “at once”, originally “on horseback”'],
  小心: ['小 small + 心 heart', 'idiomatic: “be careful” — keep your heart attentive'],
  放心: ['放 set down + 心 heart', 'figurative: to be at ease'],
  开心: ['开 open + 心 heart', 'figurative: happy'],
  生气: ['生 produce + 气 qi', 'idiomatic: to get angry'],
  大家: ['大 big + 家 household', 'idiomatic: everyone'],
  打算: ['打 do + 算 calculate', '打 is a light verb “do” here, not “hit”'],
  难过: ['难 hard + 过 to pass', 'figurative: sad — “hard to get through”'],
  // pure phonetic loans — the characters only carry sound
  咖啡: ['咖 + 啡, sound-borrowing', 'phonetic loan of “coffee” — characters carry only sound'],
  巧克力: ['巧 + 克 + 力, sound-borrowing', 'phonetic loan of “chocolate”'],
  沙发: ['沙 + 发, sound-borrowing', 'phonetic loan of “sofa”'],
  幽默: ['幽 + 默, sound-borrowing', 'phonetic loan of “humour”'],
  可乐: ['可 able + 乐 joy', 'phonetic loan of “cola”, with a lucky pun'],
};

async function zhxHandle(msg) {
  await zhxEnsureDict();
  if (msg.type === 'lookup') {
    const found = zhxIndex.get(msg.word);
    if (!found) {
      return { found: false, word: msg.word, entries: [], chars: zhxCharBreakdown(msg.word, null) };
    }
    const isProper = (e) => /^[A-Z]/.test(e.p);
    const pref = ZHX_PRIORITY[msg.word];
    const rank = (e) => (pref && e.p.toLowerCase() === pref ? -1 : isProper(e) ? 1 : 0);
    const entries = [...found].sort((a, b) => rank(a) - rank(b));
    const mode = msg.reading;
    const dialect = ZHX_READING_SLOT[mode] !== undefined;
    return {
      found: true,
      word: msg.word,
      hsk: zhxHsk[msg.word] ?? 0,
      cl: zhxClassifiers(entries),
      lit: ZHX_LITERAL[msg.word] ?? ZHX_LITERAL[entries[0].s],
      entries: entries.map((e) => ({
        s: e.s,
        t: e.t,
        p: zhxReadingFor(mode, e.p, msg.word, e.s, e.t),
        p2: dialect ? zhxAccent(e.p) : undefined,
        pn: e.p,
        defs: e.d.filter((d) => !/^CL:/.test(d)),
      })),
      chars: msg.word.length > 1 ? zhxCharBreakdown(msg.word, entries[0].p, mode) : [],
    };
  }
  if (msg.type === 'family') {
    return { char: msg.char, words: zhxFamily(msg.char, msg.word, msg.reading, msg.limit ?? 10) };
  }
  if (msg.type === 'segmentBatch') {
    return msg.texts.map((t) => zhxTokenize(t, msg.reading));
  }
  if (msg.type === 'examples') {
    zhxSentPromise ??= fetch(chrome.runtime.getURL('dict/zh/sentences.json'))
      .then((r) => r.json())
      .catch(() => ({ s: [], idx: {} }));
    const bank = await zhxSentPromise;
    const ids = bank.idx[msg.word] ?? [];
    return ids.slice(0, msg.limit ?? 2).map((id) => {
      const [cmn, eng] = bank.s[id];
      return { tokens: zhxTokenize(cmn, msg.reading), eng };
    });
  }
  throw new Error(`Unknown message type: ${msg.type}`);
}

self.LENS.register("zh", { handle: zhxHandle });
})();

// ===== ja (extension-ja) =====
(function () {
'use strict';

const ZHX_KANJI_RE = /[㐀-䶿一-鿿々]/;
const ZHX_JA_RE = /[㐀-䶿一-鿿々ぁ-ゖァ-ヺーゝゞ]/;
const ZHX_JA_RUN = /[㐀-䶿一-鿿々ぁ-ゖァ-ヺーゝゞ]+/g;

function zhxKataToHira(s) {
  return s.replace(/[ァ-ヶ]/g, (ch) => String.fromCharCode(ch.charCodeAt(0) - 0x60));
}

const ZHX_DEINFLECT = [
  ['ませんでした', ['ます']], ['ましょう', ['ます']], ['ません', ['ます']], ['ました', ['ます']],
  ['ていました', ['て']], ['でいました', ['で']], ['ています', ['て']], ['でいます', ['で']],
  ['ていた', ['て']], ['でいた', ['で']], ['ている', ['て']], ['でいる', ['で']],
  ['てる', ['て']], ['でる', ['で']],
  ['きます', ['く', 'くる']], ['ぎます', ['ぐ']], ['します', ['す', 'する']], ['ちます', ['つ']],
  ['にます', ['ぬ']], ['びます', ['ぶ']], ['みます', ['む']], ['ります', ['る']], ['います', ['う']],
  ['ます', ['る']],
  ['かった', ['い']], ['くない', ['い']], ['くて', ['い']], ['くなかった', ['い']],
  ['った', ['う', 'つ', 'る']], ['いた', ['く']], ['いだ', ['ぐ']], ['んだ', ['ぬ', 'ぶ', 'む']],
  ['って', ['う', 'つ', 'る']], ['いて', ['く']], ['いで', ['ぐ']], ['んで', ['ぬ', 'ぶ', 'む']],
  ['かない', ['く']], ['がない', ['ぐ']], ['さない', ['す']], ['たない', ['つ']], ['なない', ['ぬ']],
  ['ばない', ['ぶ']], ['まない', ['む']], ['らない', ['る']], ['わない', ['う']],
  ['した', ['す', 'する']], ['して', ['す', 'する']], ['しない', ['する']],
  ['たい', ['る']], ['なかった', ['ない', 'る']], ['ない', ['る']],
  // Causative (せる/させる)
  ['させる', ['す', 'る', 'する']], ['かせる', ['く']], ['がせる', ['ぐ']], ['たせる', ['つ']],
  ['なせる', ['ぬ']], ['ばせる', ['ぶ']], ['ませる', ['む']], ['らせる', ['る']], ['わせる', ['う']],
  // Passive / potential (れる/られる)
  ['られる', ['る']], ['かれる', ['く']], ['がれる', ['ぐ']], ['される', ['す', 'する']], ['たれる', ['つ']],
  ['なれる', ['ぬ']], ['ばれる', ['ぶ']], ['まれる', ['む']], ['われる', ['う']],
  // Volitional (よう/おう)
  ['しよう', ['する']], ['よう', ['る']], ['こう', ['く']], ['ごう', ['ぐ']], ['そう', ['す']], ['とう', ['つ']],
  ['のう', ['ぬ']], ['ぼう', ['ぶ']], ['もう', ['む']], ['ろう', ['る']], ['おう', ['う']],
  // Imperative (godan え-row, ichidan ろ/よ)
  ['ろ', ['る']], ['よ', ['る']], ['け', ['く']], ['げ', ['ぐ']], ['せ', ['す']], ['ね', ['ぬ']],
  ['べ', ['ぶ']], ['め', ['む']], ['れ', ['る']], ['え', ['う']],
  // Conditional -ば
  ['ければ', ['い']], ['けば', ['く']], ['げば', ['ぐ']], ['せば', ['す']], ['てば', ['つ']], ['ねば', ['ぬ']],
  ['べば', ['ぶ']], ['めば', ['む']], ['れば', ['る']], ['えば', ['う']],
  // Conditional -たら/-だら
  ['かったら', ['い']], ['ったら', ['う', 'つ', 'る']], ['いたら', ['く']], ['いだら', ['ぐ']],
  ['んだら', ['ぬ', 'ぶ', 'む']], ['したら', ['す', 'する']], ['だら', ['で']], ['たら', ['る']],
  ['た', ['る']], ['て', ['る']],
];

// Suppletive/irregular full forms that the suffix rules can't reach (empty stem).
const ZHX_IRREGULAR = {
  きます: '来る', きました: '来る', きません: '来る', きて: '来る', こない: '来る', こなかった: '来る',
  こよう: '来る', こい: '来る', くれば: '来る', きたい: '来る',
  // 行く is the classic irregular: its past uses っ (行った, not 行いた).
  行った: '行く', 行って: '行く', 行ったら: '行く', 行ったり: '行く', 行っても: '行く',
  いった: '行く', いって: '行く', いったら: '行く',
};

let zhxIndex = null;
let zhxKanji = null;
let zhxDictPromise = null;
let zhxSentPromise = null;
let zhxSegmenter = null;
let zhxNamesPromise = null;

function zhxEnsureNames() {
  zhxNamesPromise ??= fetch(chrome.runtime.getURL('dict/ja/names.json'))
    .then((r) => r.json())
    .then((rows) => {
      const idx = new Map();
      for (const [k, r, g, t] of rows) {
        const entry = { k, r, g, t };
        const list = idx.get(k);
        if (list) { if (list.length < 4) list.push(entry); } else idx.set(k, [entry]);
      }
      return idx;
    })
    .catch(() => new Map());
  return zhxNamesPromise;
}

function zhxEnsureDict() {
  zhxDictPromise ??= (async () => {
    const [dictRes, kanjiRes] = await Promise.all([
      fetch(chrome.runtime.getURL('dict/ja/jdict.json')),
      fetch(chrome.runtime.getURL('dict/ja/kanji.json')).catch(() => null),
    ]);
    const rows = await dictRes.json();
    zhxKanji = kanjiRes && kanjiRes.ok ? await kanjiRes.json() : {};
    zhxIndex = new Map();
    const add = (key, entry) => {
      const list = zhxIndex.get(key);
      if (list) list.push(entry); else zhxIndex.set(key, [entry]);
    };
    for (const [kebs, rebs, senses, common] of rows) {
      const entry = { k: kebs, r: rebs, s: senses, c: common };
      for (const k of kebs) add(k, entry);
      for (const r of rebs) add(r, entry);
    }
    zhxSegmenter = new Intl.Segmenter('ja', { granularity: 'word' });
  })();
  return zhxDictPromise;
}

function zhxBest(entries, word) {
  // Match against ALL written/reading forms (not just k[0]): 五月 lives at k[1] of the
  // common ごがつ entry, so k[0]-only checks made the rare さつき reading win.
  const primary = (e) => (word && (e.k.includes(word) || e.r.includes(word)) ? 1 : 0);
  return [...entries].sort((a, b) => (primary(b) - primary(a)) || (b.c - a.c) || (b.s.length - a.s.length));
}

// Word families: kanji are shared morphemes, so the vocabulary built from one kanji
// (学 → 学校 / 大学 / 学習) is how Japanese words cluster. Built lazily from the index.
let zhxKanjiWords = null;
function zhxBuildKanjiIndex() {
  if (zhxKanjiWords) return;
  zhxKanjiWords = new Map();
  for (const key of zhxIndex.keys()) {
    if (key.length < 2 || key.length > 6 || !ZHX_KANJI_RE.test(key)) continue;
    for (const ch of new Set(key)) {
      if (!ZHX_KANJI_RE.test(ch)) continue;
      let list = zhxKanjiWords.get(ch);
      if (!list) { list = new Set(); zhxKanjiWords.set(ch, list); }
      list.add(key);
    }
  }
}
function zhxFamily(kanji, exclude, limit) {
  zhxBuildKanjiIndex();
  const cand = [...(zhxKanjiWords.get(kanji) ?? [])]
    .filter((w) => w !== exclude)
    .map((w) => ({ w, e: zhxBest(zhxIndex.get(w), w)[0] }))
    .filter((x) => x.e && x.e.k.includes(x.w)); // kanji headwords only, not reading keys
  cand.sort((a, b) => (b.e.c - a.e.c) || (a.w.length - b.w.length) || a.w.localeCompare(b.w));
  const out = [];
  const seenReading = new Set(); // drop kyūjitai duplicates (發電/発電 share はつでん)
  for (const { w, e } of cand) {
    const read = zhxKataToHira(e.r[0] ?? '');
    if (seenReading.has(read)) continue;
    seenReading.add(read);
    out.push({ w, p: read, g: (e.s[0] ?? '').replace(/^to /, ''), h: e.c });
    if (out.length >= (limit ?? 12)) break;
  }
  return out;
}

function zhxDeinflect(word) {
  const seen = new Set([word]);
  const queue = [word];
  const out = [word];
  if (ZHX_IRREGULAR[word]) out.push(ZHX_IRREGULAR[word]);
  for (let depth = 0; depth < 5 && queue.length; depth++) {
    const level = queue.splice(0, queue.length);
    for (const w of level) {
      const push = (cand) => {
        if (cand && !seen.has(cand)) {
          seen.add(cand);
          queue.push(cand);
          out.push(cand);
        }
      };
      for (const [suffix, bases] of ZHX_DEINFLECT) {
        if (w.length > suffix.length && w.endsWith(suffix)) {
          for (const base of bases) push(w.slice(0, -suffix.length) + base);
        }
      }
      if (w.length > 2 && w.endsWith('する')) push(w.slice(0, -2));
      // Masu-stem of a する-verb (勉強し → 勉強). Guard against stripping the て-form's
      // し (食べてし…) by requiring the char before し to be a kanji.
      if (w.length > 2 && w.endsWith('し') && ZHX_KANJI_RE.test(w[w.length - 2])) push(w.slice(0, -1));
    }
  }
  return out;
}

function zhxLookupDeinflected(surface) {
  for (const cand of zhxDeinflect(surface)) {
    const entries = zhxIndex.get(cand);
    if (entries) return { matched: cand, entries: zhxBest(entries, cand) };
  }
  return null;
}

function zhxAlignReading(headword, reading) {
  const parts = [];
  let re = '^';
  for (const piece of headword.match(/[㐀-䶿一-鿿々]+|[^㐀-䶿一-鿿々]+/g) ?? []) {
    if (ZHX_KANJI_RE.test(piece)) {
      parts.push({ text: piece, kanji: true });
      re += '(.+?)';
    } else {
      parts.push({ text: piece, kanji: false });
      re += piece.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    }
  }
  re += '$';
  const m = zhxKataToHira(reading).match(new RegExp(re));
  if (!m) return null;
  let g = 1;
  return parts.map((p) => [p.text, p.kanji ? m[g++] : null]);
}

function zhxFurigana(surface, headword, reading) {
  const align = zhxAlignReading(headword, reading);
  if (!align) {
    return ZHX_KANJI_RE.test(surface) && surface === headword
      ? [[surface, zhxKataToHira(reading)]]
      : [[surface, null]];
  }
  const clusterReadings = align.filter(([, r]) => r !== null).map(([, r]) => r);
  const surfaceParts = surface.match(/[㐀-䶿一-鿿々]+|[^㐀-䶿一-鿿々]+/g) ?? [surface];
  const surfaceClusters = surfaceParts.filter((p) => ZHX_KANJI_RE.test(p));
  if (surfaceClusters.length !== clusterReadings.length) return [[surface, null]];
  let i = 0;
  return surfaceParts.map((p) => (ZHX_KANJI_RE.test(p) ? [p, clusterReadings[i++]] : [p, null]));
}

function zhxSegmentRun(run) {
  const segs = [...zhxSegmenter.segment(run)].map((s) => s.segment);
  const tokens = [];
  let i = 0;
  while (i < segs.length) {
    const surface = segs[i];
    if (!ZHX_JA_RE.test(surface)) {
      tokens.push({ w: surface, p: null, han: false });
      i++;
      continue;
    }
    let merged = surface;
    let consumed = 1;
    let hit = null;
    if (ZHX_KANJI_RE.test(surface)) {
      let ext = 0;
      for (let j = i + 1; j < segs.length && j <= i + 4; j++) {
        if (ZHX_KANJI_RE.test(segs[j]) || !ZHX_JA_RE.test(segs[j])) break;
        ext = j - i;
      }
      for (let e = ext; e >= 0; e--) {
        const cand = segs.slice(i, i + e + 1).join('');
        const candHit = zhxLookupDeinflected(cand);
        if (candHit) { merged = cand; consumed = e + 1; hit = candHit; break; }
      }
    } else {
      hit = zhxLookupDeinflected(surface);
    }
    if (!hit) {
      tokens.push({ w: merged, p: null, han: true, h: 0, f: [[merged, null]] });
      i += consumed;
      continue;
    }
    const entry = hit.entries[0];
    const hasKanji = ZHX_KANJI_RE.test(merged);
    const headword = entry.k.length && hasKanji ? entry.k[0] : hit.matched;
    const reading = zhxKataToHira(entry.r[0]);
    const f = hasKanji ? zhxFurigana(merged, headword, entry.r[0]) : [[merged, null]];
    tokens.push({
      w: merged,
      p: hasKanji ? reading : null,
      han: true,
      h: 0,
      f,
      base: hit.matched !== merged ? hit.matched : undefined,
    });
    i += consumed;
  }
  return tokens;
}

function zhxTokenize(text) {
  const tokens = [];
  let last = 0;
  for (const m of text.matchAll(ZHX_JA_RUN)) {
    if (m.index > last) tokens.push({ w: text.slice(last, m.index), p: null, han: false });
    tokens.push(...zhxSegmentRun(m[0]));
    last = m.index + m[0].length;
  }
  if (last < text.length) tokens.push({ w: text.slice(last), p: null, han: false });
  return tokens;
}

function zhxKanjiInfo(ch) {
  const k = zhxKanji[ch];
  if (!k) return null;
  const [on, kun, meanings] = k;
  return { on, kun, meanings };
}

async function zhxHandle(msg) {
  await zhxEnsureDict();
  if (msg.type === 'lookup') {
    const hit = zhxLookupDeinflected(msg.word);
    const kinfo = msg.word.length === 1 ? zhxKanjiInfo(msg.word) : null;
    const entries = [];
    if (hit) {
      for (const e of hit.entries.slice(0, 3)) {
        entries.push({
          s: e.k[0] ?? e.r[0],
          t: e.k[0] ?? e.r[0],
          p: zhxKataToHira(e.r[0]),
          defs: e.s,
          common: !!e.c,
        });
      }
    }
    if (!hit && !kinfo) {
      const names = await zhxEnsureNames();
      for (const n of names.get(msg.word) ?? []) {
        entries.push({
          s: n.k,
          t: n.k,
          p: zhxKataToHira(n.r),
          defs: [`(${n.t}) ${n.g}`],
        });
      }
    }
    if (kinfo) {
      entries.push({
        s: msg.word,
        t: msg.word,
        p: [...kinfo.kun.slice(0, 2), ...kinfo.on.slice(0, 2)].join('、'),
        defs: [`kanji: ${kinfo.meanings.join(', ')}`,
          kinfo.on.length ? `on: ${kinfo.on.join('、')}` : null,
          kinfo.kun.length ? `kun: ${kinfo.kun.join('、')}` : null].filter(Boolean),
      });
    }
    if (!entries.length) {
      return { found: false, word: msg.word, entries: [], chars: [] };
    }
    const chars = [...msg.word].filter((ch) => ZHX_KANJI_RE.test(ch)).map((ch) => {
      const k = zhxKanjiInfo(ch);
      return {
        ch,
        p: k ? [k.kun[0], k.on[0]].filter(Boolean).join('・') : null,
        gloss: k ? k.meanings.slice(0, 3).join(', ') : null,
      };
    });
    return {
      found: true,
      word: msg.word,
      base: hit && hit.matched !== msg.word ? hit.matched : undefined,
      hsk: 0,
      common: entries.some((e) => e.common),
      entries,
      chars: msg.word.length > 1 ? chars : [],
    };
  }
  if (msg.type === 'family') {
    return { char: msg.char, words: zhxFamily(msg.char, msg.word, msg.limit ?? 12) };
  }
  if (msg.type === 'segmentBatch') {
    return msg.texts.map(zhxTokenize);
  }
  if (msg.type === 'examples') {
    zhxSentPromise ??= fetch(chrome.runtime.getURL('dict/ja/sentences.json'))
      .then((r) => r.json())
      .catch(() => ({ s: [], idx: {} }));
    const bank = await zhxSentPromise;
    const ids = bank.idx[msg.word] ?? [];
    return ids.slice(0, msg.limit ?? 2).map((id) => {
      const [jpn, eng] = bank.s[id];
      return { tokens: zhxTokenize(jpn), eng };
    });
  }
  throw new Error(`Unknown message type: ${msg.type}`);
}

self.LENS.register("ja", { handle: zhxHandle });
})();

// ===== ko (extension-ko) =====
(function () {
'use strict';

const ZHX_HANGUL_RE = /[가-힣]/;
const ZHX_HANGUL_RUN = /[가-힣]+/g;

const ZHX_INITIALS = ['g', 'kk', 'n', 'd', 'tt', 'r', 'm', 'b', 'pp', 's', 'ss', '', 'j', 'jj', 'ch', 'k', 't', 'p', 'h'];
const ZHX_MEDIALS = ['a', 'ae', 'ya', 'yae', 'eo', 'e', 'yeo', 'ye', 'o', 'wa', 'wae', 'oe', 'yo', 'u', 'wo', 'we', 'wi', 'yu', 'eu', 'ui', 'i'];
const ZHX_FINAL_JAMO = ['', 'ㄱ', 'ㄲ', 'ㄳ', 'ㄴ', 'ㄵ', 'ㄶ', 'ㄷ', 'ㄹ', 'ㄺ', 'ㄻ', 'ㄼ', 'ㄽ', 'ㄾ', 'ㄿ', 'ㅀ', 'ㅁ', 'ㅂ', 'ㅄ', 'ㅅ', 'ㅆ', 'ㅇ', 'ㅈ', 'ㅊ', 'ㅋ', 'ㅌ', 'ㅍ', 'ㅎ'];
const ZHX_FINAL_END = { '': '', 'ㄱ': 'k', 'ㄲ': 'k', 'ㄳ': 'k', 'ㄴ': 'n', 'ㄵ': 'n', 'ㄶ': 'n', 'ㄷ': 't', 'ㄹ': 'l', 'ㄺ': 'k', 'ㄻ': 'm', 'ㄼ': 'l', 'ㄽ': 'l', 'ㄾ': 'l', 'ㄿ': 'p', 'ㅀ': 'l', 'ㅁ': 'm', 'ㅂ': 'p', 'ㅄ': 'p', 'ㅅ': 't', 'ㅆ': 't', 'ㅇ': 'ng', 'ㅈ': 't', 'ㅊ': 't', 'ㅋ': 'k', 'ㅌ': 't', 'ㅍ': 'p', 'ㅎ': 't' };
const ZHX_FINAL_LIAISON = { '': '', 'ㄱ': 'g', 'ㄲ': 'kk', 'ㄳ': 'ks', 'ㄴ': 'n', 'ㄵ': 'nj', 'ㄶ': 'n', 'ㄷ': 'd', 'ㄹ': 'r', 'ㄺ': 'lg', 'ㄻ': 'lm', 'ㄼ': 'lb', 'ㄽ': 'ls', 'ㄾ': 'lt', 'ㄿ': 'lp', 'ㅀ': 'r', 'ㅁ': 'm', 'ㅂ': 'b', 'ㅄ': 'ps', 'ㅅ': 's', 'ㅆ': 'ss', 'ㅇ': 'ng', 'ㅈ': 'j', 'ㅊ': 'ch', 'ㅋ': 'k', 'ㅌ': 't', 'ㅍ': 'p', 'ㅎ': '' };
function zhxDecompose(ch) {
  const code = ch.charCodeAt(0) - 0xAC00;
  if (code < 0 || code > 11171) return null;
  return {
    initial: Math.floor(code / 588),
    medial: Math.floor((code % 588) / 28),
    final: ZHX_FINAL_JAMO[code % 28],
  };
}

const ZHX_ASP_INITIAL = { g: 'k', d: 't', b: 'p', j: 'ch' };

function zhxRomanizeRun(run) {
  const syls = [...run].map(zhxDecompose);
  let out = '';
  for (let i = 0; i < syls.length; i++) {
    const s = syls[i];
    if (!s) { out += run[i]; continue; }
    const prev = syls[i - 1] ?? null;
    const next = syls[i + 1] ?? null;
    let initial = ZHX_INITIALS[s.initial];

    if (prev && prev.final) {
      const pf = prev.final;
      const pfEnd = ZHX_FINAL_END[pf];
      if (initial === '') {
        initial = pf === 'ㅇ' ? '' : ZHX_FINAL_LIAISON[pf];
        if ((initial === 't' || initial === 'd') && ZHX_MEDIALS[s.medial] === 'i') {
          initial = initial === 't' ? 'ch' : 'j';
        }
      } else if ((pf === 'ㅎ' || pf === 'ㄶ' || pf === 'ㅀ') && ZHX_ASP_INITIAL[initial]) {
        // ㅎ (also inside clusters ㄶ/ㅀ) aspirates a following ㄱ/ㄷ/ㅂ/ㅈ: 않다→anta, 싫다→silta.
        initial = ZHX_ASP_INITIAL[initial];
      } else if (initial === 'h' && 'ktp'.includes(pfEnd)) {
        initial = pfEnd;
      } else if (initial === 'r') {
        initial = (pf === 'ㄹ' || pf === 'ㄴ') ? 'l' : 'n';
      } else if (initial === 'n' && pf === 'ㄹ') {
        initial = 'l';
      }
    }

    let final = '';
    if (s.final) {
      const f = s.final;
      const fEnd = ZHX_FINAL_END[f];
      if (!next) {
        final = fEnd;
      } else {
        const ni = ZHX_INITIALS[next.initial];
        if (ni === '') {
          final = f === 'ㅇ' ? 'ng' : '';
        } else if (f === 'ㅎ') {
          final = (ni === 'n' || ni === 'm') ? 'n' : '';
        } else if (ni === 'n' || ni === 'm') {
          final = fEnd === 'k' ? 'ng' : fEnd === 't' ? 'n' : fEnd === 'p' ? 'm' : fEnd;
        } else if (ni === 'r') {
          // Before an ㄹ-initial, an obstruent final nasalizes: 국립→gungnip, 협력→hyeomnyeok.
          if (f === 'ㄴ') final = 'l';
          else final = fEnd === 'k' ? 'ng' : fEnd === 't' ? 'n' : fEnd === 'p' ? 'm' : fEnd;
        } else if (ni === 'h' && 'ktp'.includes(fEnd)) {
          final = '';
        } else {
          final = fEnd;
        }
      }
    }
    out += initial + ZHX_MEDIALS[s.medial] + final;
  }
  return out;
}

const ZHX_PARTICLES = ['에서는', '에서도', '에서', '에게서', '에게', '한테', '께서', '으로써', '으로서', '으로', '로써', '로서', '부터', '까지', '처럼', '보다', '마다', '조차', '밖에', '하고', '이랑', '이나', '라고', '이라고', '은', '는', '이', '가', '을', '를', '에', '의', '도', '만', '와', '과', '로', '랑', '나', '요'];
const ZHX_VERB_TAILS = [
  ['했습니다', '하다'], ['했어요', '하다'], ['합니다', '하다'], ['했다', '하다'], ['해요', '하다'],
  ['하고', '하다'], ['하는', '하다'], ['하며', '하다'], ['하면', '하다'], ['해서', '하다'],
  ['됐습니다', '되다'], ['됩니다', '되다'], ['됐다', '되다'], ['돼요', '되다'],
  ['었습니다', '다'], ['았습니다', '다'], ['습니다', '다'],
  ['었어요', '다'], ['았어요', '다'], ['어요', '다'], ['아요', '다'],
  ['었다', '다'], ['았다', '다'], ['는다', '다'], ['ㄴ다', '다'],
];

function zhxStripFinalB(word) {
  const last = word[word.length - 1];
  const d = zhxDecompose(last);
  if (d && d.final === 'ㅂ') {
    return word.slice(0, -1) + String.fromCharCode(0xAC00 + d.initial * 588 + d.medial * 28);
  }
  return null;
}

// Recompose a syllable with a different final jamo ('' = remove final).
function zhxSetFinal(syl, finalJamo) {
  const d = zhxDecompose(syl);
  if (!d) return null;
  const fi = ZHX_FINAL_JAMO.indexOf(finalJamo);
  if (fi < 0) return null;
  return String.fromCharCode(0xAC00 + d.initial * 588 + d.medial * 28 + fi);
}

// Common 으-irregular (vowel-contracted) stems whose surface can't be reversed by rule.
const ZHX_EU_IRREGULAR = {
  써: '쓰다', 커: '크다', 꺼: '끄다', 떠: '뜨다', 아파: '아프다', 바빠: '바쁘다',
  고파: '고프다', 예뻐: '예쁘다', 슬퍼: '슬프다', 기뻐: '기쁘다', 나빠: '나쁘다', 담가: '담그다',
};

// Reverse the ㅂ-, 르-, and 으-irregular conjugations to recover the dictionary lemma.
// (ㄷ-irregular is deliberately omitted: 들어→듣다 collides with the real word 들다.)
function zhxIrregularStems(w) {
  const res = [];
  const last = w[w.length - 1];
  if ((last === '와' || last === '워') && w.length >= 2) {
    const b = zhxSetFinal(w[w.length - 2], 'ㅂ');           // 도와→돕다, 무거워→무겁다
    if (b) res.push(w.slice(0, -2) + b + '다');
  }
  if ((last === '라' || last === '러') && w.length >= 2) {
    const prev = zhxDecompose(w[w.length - 2]);
    if (prev && prev.final === 'ㄹ') {                        // 몰라→모르다, 빨라→빠르다
      res.push(w.slice(0, -2) + zhxSetFinal(w[w.length - 2], '') + '르다');
    }
  }
  if (ZHX_EU_IRREGULAR[w]) res.push(ZHX_EU_IRREGULAR[w]);
  return res;
}

function zhxCandidates(word) {
  const out = new Set([word]);
  const seen = new Set([word]);
  const queue = [word];
  let guard = 0;
  const enqueue = (s) => { if (s && s.length >= 1 && !seen.has(s)) { seen.add(s); queue.push(s); } };
  while (queue.length && guard++ < 40) {
    const w = queue.pop();
    out.add(w);
    // Strip a trailing particle and re-queue, so stacked particles peel (학교로부터→학교).
    for (const p of ZHX_PARTICLES) {
      if (w.length > p.length && w.endsWith(p)) enqueue(w.slice(0, -p.length));
    }
    // Verb/adjective endings → dictionary base form.
    for (const [tail, base] of ZHX_VERB_TAILS) {
      if (w.length > tail.length && w.endsWith(tail)) out.add(w.slice(0, -tail.length) + base);
    }
    if (w.endsWith('니다')) { const st = zhxStripFinalB(w.slice(0, -2)); if (st) out.add(st + '다'); }
    for (const c of zhxIrregularStems(w)) out.add(c);
  }
  if (word.length > 2) out.add(word.slice(0, -1));
  return [...out];
}

let zhxIndex = null;
let zhxDictPromise = null;
let zhxSentPromise = null;

function zhxEnsureDict() {
  zhxDictPromise ??= (async () => {
    const res = await fetch(chrome.runtime.getURL('dict/ko/kodict.json'));
    const rows = await res.json();
    zhxIndex = new Map();
    for (const [word, hanja, gloss] of rows) {
      const entry = { w: word, h: hanja, g: gloss };
      const list = zhxIndex.get(word);
      if (list) { if (list.length < 6) list.push(entry); } else zhxIndex.set(word, [entry]);
    }
  })();
  return zhxDictPromise;
}

function zhxLookupStem(word) {
  for (const cand of zhxCandidates(word)) {
    const entries = zhxIndex.get(cand);
    if (entries) return { matched: cand, entries };
  }
  return null;
}

// Word families: Sino-Korean vocabulary clusters around shared syllables (학 → 학생·학교·
// 대학), most of which trace to one hanja. Indexed lazily by Hangul syllable; each family
// word carries the hanja aligned to the shared syllable so 學-words separate from homophones.
let zhxSylWords = null;
function zhxBuildSylIndex() {
  if (zhxSylWords) return;
  zhxSylWords = new Map();
  for (const word of zhxIndex.keys()) {
    if (word.length < 2 || word.length > 5) continue;
    for (const ch of new Set(word)) {
      if (!ZHX_HANGUL_RE.test(ch)) continue;
      let list = zhxSylWords.get(ch);
      if (!list) { list = []; zhxSylWords.set(ch, list); }
      list.push(word);
    }
  }
}
function zhxSylHanja(word, syl) {
  const hanja = (zhxIndex.get(word) ?? []).find((e) => e.h && e.h.length === word.length)?.h;
  if (!hanja) return '';
  const i = word.indexOf(syl);
  return i >= 0 ? hanja[i] : '';
}
function zhxFamily(syl, exclude, limit, freq) {
  zhxBuildSylIndex();
  const f = freq ?? {};
  const cand = [...new Set(zhxSylWords.get(syl) ?? [])].filter((w) => w !== exclude);
  const rows = cand.map((w) => {
    const e = zhxIndex.get(w)[0];
    return { w, p: zhxRomanizeRun(w), g: e.g ?? '', hanja: zhxSylHanja(w, syl), n: f[w] ?? 0 };
  });
  // No frequency table in the KO dict; use the example-sentence bank as a mild popularity
  // signal (학교/과학 appear, 균학 doesn't), then fall back to length + alphabetical order.
  rows.sort((a, b) => b.n - a.n || a.w.length - b.w.length || a.w.localeCompare(b.w));
  return rows.slice(0, limit ?? 12).map((r) => ({
    w: r.w, p: r.p, g: r.hanja ? `${r.hanja} · ${r.g}` : r.g, h: 0,
  }));
}

function zhxTokenize(text) {
  const tokens = [];
  let last = 0;
  for (const m of text.matchAll(ZHX_HANGUL_RUN)) {
    if (m.index > last) tokens.push({ w: text.slice(last, m.index), p: null, han: false });
    tokens.push({ w: m[0], p: zhxRomanizeRun(m[0]), han: true, h: 0 });
    last = m.index + m[0].length;
  }
  if (last < text.length) tokens.push({ w: text.slice(last), p: null, han: false });
  return tokens;
}

async function zhxHandle(msg) {
  await zhxEnsureDict();
  if (msg.type === 'lookup') {
    const hit = zhxLookupStem(msg.word);
    if (!hit) {
      return {
        found: false,
        word: msg.word,
        entries: [],
        chars: [...msg.word].filter((c) => ZHX_HANGUL_RE.test(c)).map((ch) => ({ ch, p: zhxRomanizeRun(ch), gloss: null })),
      };
    }
    const hanja = hit.entries.find((e) => e.h)?.h ?? '';
    const hanjaAligned = hanja.length === hit.matched.length ? [...hanja] : null;
    return {
      found: true,
      word: msg.word,
      base: hit.matched !== msg.word ? hit.matched : undefined,
      hsk: 0,
      entries: [{
        s: hit.matched,
        t: hanja || hit.matched,
        p: zhxRomanizeRun(hit.matched),
        defs: hit.entries.map((e) => e.g + (e.h ? ` (${e.h})` : '')).slice(0, 6),
      }],
      chars: hit.matched.length > 1
        ? [...hit.matched].map((ch, i) => ({
            ch,
            p: zhxRomanizeRun(ch),
            gloss: hanjaAligned ? `hanja ${hanjaAligned[i]}` : null,
          }))
        : [],
    };
  }
  if (msg.type === 'family') {
    zhxSentPromise ??= fetch(chrome.runtime.getURL('dict/ko/sentences.json'))
      .then((r) => r.json())
      .catch(() => ({ s: [], idx: {} }));
    const bank = await zhxSentPromise;
    const freq = Object.fromEntries(Object.entries(bank.idx ?? {}).map(([w, ids]) => [w, ids.length]));
    return { char: msg.char, words: zhxFamily(msg.char, msg.word, msg.limit ?? 12, freq) };
  }
  if (msg.type === 'segmentBatch') {
    return msg.texts.map(zhxTokenize);
  }
  if (msg.type === 'examples') {
    zhxSentPromise ??= fetch(chrome.runtime.getURL('dict/ko/sentences.json'))
      .then((r) => r.json())
      .catch(() => ({ s: [], idx: {} }));
    const bank = await zhxSentPromise;
    const ids = bank.idx[msg.word] ?? [];
    return ids.slice(0, msg.limit ?? 2).map((id) => {
      const [kor, eng] = bank.s[id];
      return { tokens: zhxTokenize(kor), eng };
    });
  }
  throw new Error(`Unknown message type: ${msg.type}`);
}

self.LENS.register("ko", { handle: zhxHandle });
})();

// ===== ar (extension-ar) =====
(function () {
'use strict';

const ZHX_WORD_RUN = /[\u0600-\u06FF\u0750-\u077F]+/g;
function zhxBare(w) { return (w ?? '').replace(/[\u064B-\u065F\u0670\u0640\u05B0-\u05BD\u05C1\u05C2\u05C7]/g, ''); }
const ZHX_TR = { 'ا': 'a', 'ب': 'b', 'ت': 't', 'ث': 'th', 'ج': 'j', 'ح': 'h', 'خ': 'kh', 'د': 'd', 'ذ': 'dh', 'ر': 'r', 'ز': 'z', 'س': 's', 'ش': 'sh', 'ص': 's', 'ض': 'd', 'ط': 't', 'ظ': 'z', 'ع': "'", 'غ': 'gh', 'ف': 'f', 'ق': 'q', 'ك': 'k', 'ل': 'l', 'م': 'm', 'ن': 'n', 'ه': 'h', 'و': 'w', 'ي': 'y', 'ء': "'", 'آ': 'aa', 'ة': 'a', 'ى': 'a', 'أ': 'a', 'إ': 'i', 'ئ': "'", 'ؤ': "'" };
function zhxTranslit(word) {
  const SUN = 'تثدذرزسشصضطظلن';
  const plain = (w) => { let o = ''; for (const ch of w) o += ZHX_TR[ch] ?? ''; return o; };
  if (word.startsWith('ال') && word.length > 2) {
    // Definite article: the ل assimilates before a sun letter (الشمس → ash-shms),
    // stays "al-" before a moon letter (الكتاب → al-ktab).
    return SUN.includes(word[2]) ? 'a' + (ZHX_TR[word[2]] ?? '') + '-' + plain(word.slice(2)) : 'al-' + plain(word.slice(2));
  }
  return plain(word);
}

const ZHX_PREFIXES = ['ال', 'وال', 'بال', 'كال', 'فال', 'لل', 'و', 'ف', 'ب', 'ك', 'ل'];
function zhxCandidates(word) {
  const bare = zhxBare(word);
  const out = [bare];
  for (const p of ZHX_PREFIXES) {
    if (bare.length > p.length + 1 && bare.startsWith(p)) out.push(bare.slice(p.length));
  }
  return [...new Set(out)];
}
// Token readings come only from the dictionary. Unvocalized Arabic has no written
// short vowels, so letter-mapping an unknown word yields consonant soup ("mdrsa") — worse
// than no reading. When a word is a clitic + known base (والقاموس = wa + al + qamus), the
// reading is composed from the prefix's romanization and the base's dictionary reading.
const ZHX_PREFIX_ROMAN = [['وال', 'wal-'], ['بال', 'bil-'], ['كال', 'kal-'], ['فال', 'fal-'], ['لل', 'lil-'], ['ال', 'al-'], ['و', 'wa-'], ['ف', 'fa-'], ['ب', 'bi-'], ['ك', 'ka-'], ['ل', 'li-']];
const ZHX_SUN_CLUSTER = /^(sh|th|dh|[tdrzsln])/; // Arabic definite-article assimilation
function zhxTokenReading(run) {
  const bare = zhxBare(run);
  const exact = (zhxIndex.get(bare) ?? [])[0];
  if (exact?.x) return exact.x;
  for (const [p, roman] of ZHX_PREFIX_ROMAN) {
    if (bare.length > p.length + 2 && bare.startsWith(p)) {
      const base = (zhxIndex.get(bare.slice(p.length)) ?? [])[0];
      if (base?.x) {
        if (roman.endsWith('l-')) {
          const sun = base.x.match(ZHX_SUN_CLUSTER);
          if (sun) return roman.slice(0, -2) + sun[1] + '-' + base.x;
        }
        return roman + base.x;
      }
    }
  }
  return null;
}

let zhxIndex = null;
let zhxDictPromise = null;
let zhxSentPromise = null;

function zhxEnsureDict() {
  zhxDictPromise ??= (async () => {
    const rows = await (await fetch(chrome.runtime.getURL('dict/ar/dict.json'))).json();
    zhxIndex = new Map();
    const add = (key, entry) => {
      if (!key) return;
      const list = zhxIndex.get(key);
      if (list) { if (list.length < 8) list.push(entry); } else zhxIndex.set(key, [entry]);
    };
    for (const [w, extra, gloss] of rows) {
      const entry = { w, x: extra, g: gloss };
      add(zhxBare(w), entry);
    }
  })();
  return zhxDictPromise;
}

// A gloss that is only a grammatical pointer ("(verb) inflection of estar") with no
// real definition. These should rank below entries that actually define the word.
const ZHX_POINTER_RE = /^(\([^)]*\)\s*)?(inflection|plural|singular|feminine|masculine|neuter|comparative|superlative|diminutive|augmentative|past participle|present participle|gerund|infinitive|conjugation|imperative|subjunctive|indicative|preterite|first-person|second-person|third-person|nominative|genitive|dative|accusative|vocative|construct|dual|alternative)\b[^;]*\bof\b/i;
function zhxRankList(list) {
  return [...list].sort((a, b) => (ZHX_POINTER_RE.test(a.g) ? 1 : 0) - (ZHX_POINTER_RE.test(b.g) ? 1 : 0));
}

function zhxLookupWord(word) {
  const bare = zhxBare(word);
  for (const cand of zhxCandidates(word)) {
    const list = zhxIndex.get(cand);
    if (list) {
      // A match reached only by removing a single leading clitic letter (Arabic و/ف/ب/ك/ل,
      // Hebrew single-letter proclitics) is unreliable — it can land on an unrelated word
      // (كتبت→تبت "Tibet"). Flag it so the UI shows the result as uncertain rather than
      // confidently wrong. Multi-letter prefix strips (ال, וה) stay trusted.
      const risky = cand !== bare && bare.endsWith(cand) && bare.length - cand.length === 1;
      return { matched: cand, list, risky };
    }
  }
  return null;
}

// Reduplication note (Malay 词-doubling carries meaning): kanak-kanak = plural,
// sayur-sayuran = variety, tolong-menolong = reciprocal.
function zhxRedup(word) {
  const hy = word.indexOf('-');
  if (hy <= 0) return undefined;
  const a = word.slice(0, hy).toLowerCase();
  const b = word.slice(hy + 1).toLowerCase();
  if (a === b) return 'reduplication — plural or repetition of "' + a + '"';
  if (b === a + 'an' || b === a + 'kan') return 'reduplication — variety/collective of "' + a + '"';
  if (/^(me|men|mem|meng|meny)/.test(b) && b.length > 3) return 'reduplication — reciprocal (doing "' + a + '" to one another)';
  return undefined;
}

function zhxTokenize(text) {
  const tokens = [];
  let last = 0;
  for (const m of text.matchAll(ZHX_WORD_RUN)) {
    if (m.index > last) tokens.push({ w: text.slice(last, m.index), p: null, han: false });
    const run = m[0];
    tokens.push({ w: run, p: zhxTokenReading(run), han: true, h: 0 });
    last = m.index + run.length;
  }
  if (last < text.length) tokens.push({ w: text.slice(last), p: null, han: false });
  return tokens;
}

async function zhxHandle(msg) {
  await zhxEnsureDict();
  if (msg.type === 'lookup') {
    const hit = zhxLookupWord(msg.word);
    if (!hit) {
      return { found: false, word: msg.word, entries: [], chars: [] };
    }
    const list = zhxRankList(hit.list);
    return {
      found: true,
      word: msg.word,
      base: hit.matched !== msg.word && hit.matched !== msg.word.toLowerCase() ? hit.matched : undefined,
      tentative: !!hit.risky,
      redup: zhxRedup(msg.word),
      hsk: 0,
      entries: [{ s: list[0].w, t: list[0].w, p: list[0].x || null, defs: list.map((e) => e.g).slice(0, 8) }],
      chars: [],
    };
  }
  if (msg.type === 'segmentBatch') {
    return msg.texts.map(zhxTokenize);
  }
  if (msg.type === 'examples') {
    zhxSentPromise ??= fetch(chrome.runtime.getURL('dict/ar/sentences.json'))
      .then((r) => r.json())
      .catch(() => ({ s: [], idx: {} }));
    const bank = await zhxSentPromise;
    const ids = bank.idx[msg.word] ?? bank.idx[msg.word.toLowerCase?.() ?? msg.word] ?? [];
    return ids.slice(0, msg.limit ?? 2).map((id) => {
      const [native, eng] = bank.s[id];
      return { tokens: zhxTokenize(native), eng };
    });
  }
  throw new Error('Unknown message type: ' + msg.type);
}

self.LENS.register("ar", { handle: zhxHandle });
})();

// ===== jawi (extension-jawi) =====
(function () {
'use strict';

const ZHX_WORD_RUN = /[\u0600-\u06FF\u0750-\u077F]+/g;
function zhxBare(w) { return (w ?? '').replace(/[\u064B-\u065F\u0670\u0640\u05B0-\u05BD\u05C1\u05C2\u05C7]/g, ''); }
const ZHX_TR = { 'چ': 'c', 'ڠ': 'ng', 'ڤ': 'p', 'ݢ': 'g', 'ڽ': 'ny', 'ۏ': 'v', 'ک': 'k', 'ݣ': 'g', 'ا': 'a', 'ب': 'b', 'ت': 't', 'ث': 'th', 'ج': 'j', 'ح': 'h', 'خ': 'kh', 'د': 'd', 'ذ': 'dh', 'ر': 'r', 'ز': 'z', 'س': 's', 'ش': 'sh', 'ص': 's', 'ض': 'd', 'ط': 't', 'ظ': 'z', 'ع': "'", 'غ': 'gh', 'ف': 'f', 'ق': 'k', 'ك': 'k', 'ل': 'l', 'م': 'm', 'ن': 'n', 'ه': 'h', 'و': 'w', 'ي': 'y', 'ى': 'a', 'ء': "'", 'ة': 'h', 'ڬ': 'g' };
function zhxTranslit(word) {
  let out = '';
  for (const ch of word) out += ZHX_TR[ch] ?? '';
  return out;
}

function zhxCandidates(word) {
  return [zhxBare(word)];
}

let zhxIndex = null;
let zhxDictPromise = null;
let zhxSentPromise = null;

function zhxEnsureDict() {
  zhxDictPromise ??= (async () => {
    const rows = await (await fetch(chrome.runtime.getURL('dict/jawi/dict.json'))).json();
    zhxIndex = new Map();
    const add = (key, entry) => {
      if (!key) return;
      const list = zhxIndex.get(key);
      if (list) { if (list.length < 8) list.push(entry); } else zhxIndex.set(key, [entry]);
    };
    for (const [w, extra, gloss] of rows) {
      const entry = { w, x: extra, g: gloss };
      add(zhxBare(extra), entry); if (w) add(w.toLowerCase(), entry);
    }
  })();
  return zhxDictPromise;
}

// A gloss that is only a grammatical pointer ("(verb) inflection of estar") with no
// real definition. These should rank below entries that actually define the word.
const ZHX_POINTER_RE = /^(\([^)]*\)\s*)?(inflection|plural|singular|feminine|masculine|neuter|comparative|superlative|diminutive|augmentative|past participle|present participle|gerund|infinitive|conjugation|imperative|subjunctive|indicative|preterite|first-person|second-person|third-person|nominative|genitive|dative|accusative|vocative|construct|dual|alternative)\b[^;]*\bof\b/i;
function zhxRankList(list) {
  return [...list].sort((a, b) => (ZHX_POINTER_RE.test(a.g) ? 1 : 0) - (ZHX_POINTER_RE.test(b.g) ? 1 : 0));
}

function zhxLookupWord(word) {
  const bare = zhxBare(word);
  for (const cand of zhxCandidates(word)) {
    const list = zhxIndex.get(cand);
    if (list) {
      // A match reached only by removing a single leading clitic letter (Arabic و/ف/ب/ك/ل,
      // Hebrew single-letter proclitics) is unreliable — it can land on an unrelated word
      // (كتبت→تبت "Tibet"). Flag it so the UI shows the result as uncertain rather than
      // confidently wrong. Multi-letter prefix strips (ال, וה) stay trusted.
      const risky = cand !== bare && bare.endsWith(cand) && bare.length - cand.length === 1;
      return { matched: cand, list, risky };
    }
  }
  return null;
}

// Reduplication note (Malay 词-doubling carries meaning): kanak-kanak = plural,
// sayur-sayuran = variety, tolong-menolong = reciprocal.
function zhxRedup(word) {
  const hy = word.indexOf('-');
  if (hy <= 0) return undefined;
  const a = word.slice(0, hy).toLowerCase();
  const b = word.slice(hy + 1).toLowerCase();
  if (a === b) return 'reduplication — plural or repetition of "' + a + '"';
  if (b === a + 'an' || b === a + 'kan') return 'reduplication — variety/collective of "' + a + '"';
  if (/^(me|men|mem|meng|meny)/.test(b) && b.length > 3) return 'reduplication — reciprocal (doing "' + a + '" to one another)';
  return undefined;
}

function zhxTokenize(text) {
  const tokens = [];
  let last = 0;
  for (const m of text.matchAll(ZHX_WORD_RUN)) {
    if (m.index > last) tokens.push({ w: text.slice(last, m.index), p: null, han: false });
    const run = m[0];
    tokens.push({ w: run, p: (zhxIndex.get(zhxBare(run)) ?? [])[0]?.w ?? null, han: true, h: 0 });
    last = m.index + run.length;
  }
  if (last < text.length) tokens.push({ w: text.slice(last), p: null, han: false });
  return tokens;
}

async function zhxHandle(msg) {
  await zhxEnsureDict();
  if (msg.type === 'lookup') {
    const hit = zhxLookupWord(msg.word);
    if (!hit) {
      return { found: false, word: msg.word, entries: [], chars: [] };
    }
    const list = zhxRankList(hit.list);
    return {
      found: true,
      word: msg.word,
      base: hit.matched !== msg.word && hit.matched !== msg.word.toLowerCase() ? hit.matched : undefined,
      tentative: !!hit.risky,
      redup: zhxRedup(msg.word),
      hsk: 0,
      entries: [{ s: list[0].w, t: list[0].w, p: list[0].w, defs: list.map((e) => e.g).slice(0, 8) }],
      chars: [],
    };
  }
  if (msg.type === 'segmentBatch') {
    return msg.texts.map(zhxTokenize);
  }
  if (msg.type === 'examples') {
    zhxSentPromise ??= fetch(chrome.runtime.getURL('dict/jawi/sentences.json'))
      .then((r) => r.json())
      .catch(() => ({ s: [], idx: {} }));
    const bank = await zhxSentPromise;
    const ids = bank.idx[msg.word] ?? bank.idx[msg.word.toLowerCase?.() ?? msg.word] ?? [];
    return ids.slice(0, msg.limit ?? 2).map((id) => {
      const [native, eng] = bank.s[id];
      return { tokens: zhxTokenize(native), eng };
    });
  }
  throw new Error('Unknown message type: ' + msg.type);
}

self.LENS.register("jawi", { handle: zhxHandle });
})();

// ===== he (extension-he) =====
(function () {
'use strict';

const ZHX_WORD_RUN = /[\u0590-\u05FF''"]+/g;
function zhxBare(w) { return (w ?? '').replace(/[\u064B-\u065F\u0670\u0640\u05B0-\u05BD\u05C1\u05C2\u05C7]/g, ''); }
const ZHX_TR = { 'א': "'", 'ב': 'v', 'ג': 'g', 'ד': 'd', 'ה': 'h', 'ו': 'v', 'ז': 'z', 'ח': 'ch', 'ט': 't', 'י': 'y', 'כ': 'kh', 'ך': 'kh', 'ל': 'l', 'מ': 'm', 'ם': 'm', 'נ': 'n', 'ן': 'n', 'ס': 's', 'ע': "'", 'פ': 'f', 'ף': 'f', 'צ': 'ts', 'ץ': 'ts', 'ק': 'k', 'ר': 'r', 'ש': 'sh', 'ת': 't' };
function zhxTranslit(word) {
  // בגדכפת: ב/כ/פ are plosive (b/k/p) word-initially, fricative (v/kh/f) elsewhere.
  const PLOSIVE = { 'ב': 'b', 'כ': 'k', 'פ': 'p' };
  let out = '';
  [...word].forEach((ch, i) => { out += (i === 0 && PLOSIVE[ch]) ? PLOSIVE[ch] : (ZHX_TR[ch] ?? ''); });
  return out;
}

const ZHX_PREFIXES = ['ה', 'ו', 'ב', 'ל', 'מ', 'כ', 'ש', 'וה', 'שה', 'מה', 'בה'];
function zhxCandidates(word) {
  const bare = zhxBare(word);
  const out = [bare];
  for (const p of ZHX_PREFIXES) {
    if (bare.length > p.length + 1 && bare.startsWith(p)) out.push(bare.slice(p.length));
  }
  return [...new Set(out)];
}
// Token readings come only from the dictionary. Unvocalized Hebrew has no written
// short vowels, so letter-mapping an unknown word yields consonant soup ("mdrsa") — worse
// than no reading. When a word is a clitic + known base (والقاموس = wa + al + qamus), the
// reading is composed from the prefix's romanization and the base's dictionary reading.
const ZHX_PREFIX_ROMAN = [['וה', 'veha-'], ['שה', 'sheha-'], ['מה', 'meha-'], ['בה', 'ba-'], ['ה', 'ha-'], ['ו', 've-'], ['ב', 'be-'], ['ל', 'le-'], ['מ', 'mi-'], ['כ', 'ke-'], ['ש', 'she-']];
const ZHX_SUN_CLUSTER = /^(sh|th|dh|[tdrzsln])/; // Arabic definite-article assimilation
function zhxTokenReading(run) {
  const bare = zhxBare(run);
  const exact = (zhxIndex.get(bare) ?? [])[0];
  if (exact?.x) return exact.x;
  for (const [p, roman] of ZHX_PREFIX_ROMAN) {
    if (bare.length > p.length + 2 && bare.startsWith(p)) {
      const base = (zhxIndex.get(bare.slice(p.length)) ?? [])[0];
      if (base?.x) {
        if (roman.endsWith('l-')) {
          const sun = base.x.match(ZHX_SUN_CLUSTER);
          if (sun) return roman.slice(0, -2) + sun[1] + '-' + base.x;
        }
        return roman + base.x;
      }
    }
  }
  return null;
}

let zhxIndex = null;
let zhxDictPromise = null;
let zhxSentPromise = null;

function zhxEnsureDict() {
  zhxDictPromise ??= (async () => {
    const rows = await (await fetch(chrome.runtime.getURL('dict/he/dict.json'))).json();
    zhxIndex = new Map();
    const add = (key, entry) => {
      if (!key) return;
      const list = zhxIndex.get(key);
      if (list) { if (list.length < 8) list.push(entry); } else zhxIndex.set(key, [entry]);
    };
    for (const [w, extra, gloss] of rows) {
      const entry = { w, x: extra, g: gloss };
      add(zhxBare(w), entry);
    }
  })();
  return zhxDictPromise;
}

// A gloss that is only a grammatical pointer ("(verb) inflection of estar") with no
// real definition. These should rank below entries that actually define the word.
const ZHX_POINTER_RE = /^(\([^)]*\)\s*)?(inflection|plural|singular|feminine|masculine|neuter|comparative|superlative|diminutive|augmentative|past participle|present participle|gerund|infinitive|conjugation|imperative|subjunctive|indicative|preterite|first-person|second-person|third-person|nominative|genitive|dative|accusative|vocative|construct|dual|alternative)\b[^;]*\bof\b/i;
function zhxRankList(list) {
  return [...list].sort((a, b) => (ZHX_POINTER_RE.test(a.g) ? 1 : 0) - (ZHX_POINTER_RE.test(b.g) ? 1 : 0));
}

function zhxLookupWord(word) {
  const bare = zhxBare(word);
  for (const cand of zhxCandidates(word)) {
    const list = zhxIndex.get(cand);
    if (list) {
      // A match reached only by removing a single leading clitic letter (Arabic و/ف/ب/ك/ل,
      // Hebrew single-letter proclitics) is unreliable — it can land on an unrelated word
      // (كتبت→تبت "Tibet"). Flag it so the UI shows the result as uncertain rather than
      // confidently wrong. Multi-letter prefix strips (ال, וה) stay trusted.
      const risky = cand !== bare && bare.endsWith(cand) && bare.length - cand.length === 1;
      return { matched: cand, list, risky };
    }
  }
  return null;
}

// Reduplication note (Malay 词-doubling carries meaning): kanak-kanak = plural,
// sayur-sayuran = variety, tolong-menolong = reciprocal.
function zhxRedup(word) {
  const hy = word.indexOf('-');
  if (hy <= 0) return undefined;
  const a = word.slice(0, hy).toLowerCase();
  const b = word.slice(hy + 1).toLowerCase();
  if (a === b) return 'reduplication — plural or repetition of "' + a + '"';
  if (b === a + 'an' || b === a + 'kan') return 'reduplication — variety/collective of "' + a + '"';
  if (/^(me|men|mem|meng|meny)/.test(b) && b.length > 3) return 'reduplication — reciprocal (doing "' + a + '" to one another)';
  return undefined;
}

function zhxTokenize(text) {
  const tokens = [];
  let last = 0;
  for (const m of text.matchAll(ZHX_WORD_RUN)) {
    if (m.index > last) tokens.push({ w: text.slice(last, m.index), p: null, han: false });
    const run = m[0];
    tokens.push({ w: run, p: zhxTokenReading(run), han: true, h: 0 });
    last = m.index + run.length;
  }
  if (last < text.length) tokens.push({ w: text.slice(last), p: null, han: false });
  return tokens;
}

async function zhxHandle(msg) {
  await zhxEnsureDict();
  if (msg.type === 'lookup') {
    const hit = zhxLookupWord(msg.word);
    if (!hit) {
      return { found: false, word: msg.word, entries: [], chars: [] };
    }
    const list = zhxRankList(hit.list);
    return {
      found: true,
      word: msg.word,
      base: hit.matched !== msg.word && hit.matched !== msg.word.toLowerCase() ? hit.matched : undefined,
      tentative: !!hit.risky,
      redup: zhxRedup(msg.word),
      hsk: 0,
      entries: [{ s: list[0].w, t: list[0].w, p: list[0].x || null, defs: list.map((e) => e.g).slice(0, 8) }],
      chars: [],
    };
  }
  if (msg.type === 'segmentBatch') {
    return msg.texts.map(zhxTokenize);
  }
  if (msg.type === 'examples') {
    zhxSentPromise ??= fetch(chrome.runtime.getURL('dict/he/sentences.json'))
      .then((r) => r.json())
      .catch(() => ({ s: [], idx: {} }));
    const bank = await zhxSentPromise;
    const ids = bank.idx[msg.word] ?? bank.idx[msg.word.toLowerCase?.() ?? msg.word] ?? [];
    return ids.slice(0, msg.limit ?? 2).map((id) => {
      const [native, eng] = bank.s[id];
      return { tokens: zhxTokenize(native), eng };
    });
  }
  throw new Error('Unknown message type: ' + msg.type);
}

self.LENS.register("he", { handle: zhxHandle });
})();

// ===== fr (extension-fr) =====
(function () {
'use strict';

const ZHX_WORD_RUN = /[A-Za-zÀ-ÖØ-öø-ÿŒœÆæ'\u2019-]+/g;
function zhxBare(w) { return w; }
function zhxTranslit() { return ''; }

function zhxCandidates(word) {
  const norm = word.replace(/[\u2018\u2019]/g, "'").replace(/[\u201C\u201D]/g, '"');
  const out = [norm];
  if (norm !== word) out.push(word);
  const lower = norm.toLowerCase();
  if (lower !== norm) out.push(lower);
  const strip = lower.replace(/^['"«»¿¡(]+|['"«»¿¡?!.,;:)]+$/g, '');
  if (strip && strip !== lower) out.push(strip);
  const ap = strip.replace(/^(lorsqu|jusqu|puisqu|quoiqu|qu|l|d|j|m|t|s|n|c)'/, ''); if (ap && ap !== strip) out.push(ap);
  return [...new Set(out)];
}

let zhxIndex = null;
let zhxDictPromise = null;
let zhxSentPromise = null;

function zhxEnsureDict() {
  zhxDictPromise ??= (async () => {
    const rows = await (await fetch(chrome.runtime.getURL('dict/fr/dict.json'))).json();
    zhxIndex = new Map();
    const add = (key, entry) => {
      if (!key) return;
      const list = zhxIndex.get(key);
      if (list) { if (list.length < 8) list.push(entry); } else zhxIndex.set(key, [entry]);
    };
    for (const [w, extra, gloss] of rows) {
      const entry = { w, x: extra, g: gloss };
      add(w, entry); const lower = w.toLowerCase(); if (lower !== w) add(lower, entry);
    }
  })();
  return zhxDictPromise;
}

// A gloss that is only a grammatical pointer ("(verb) inflection of estar") with no
// real definition. These should rank below entries that actually define the word.
const ZHX_POINTER_RE = /^(\([^)]*\)\s*)?(inflection|plural|singular|feminine|masculine|neuter|comparative|superlative|diminutive|augmentative|past participle|present participle|gerund|infinitive|conjugation|imperative|subjunctive|indicative|preterite|first-person|second-person|third-person|nominative|genitive|dative|accusative|vocative|construct|dual|alternative)\b[^;]*\bof\b/i;
function zhxRankList(list) {
  return [...list].sort((a, b) => (ZHX_POINTER_RE.test(a.g) ? 1 : 0) - (ZHX_POINTER_RE.test(b.g) ? 1 : 0));
}

function zhxLookupWord(word) {
  const bare = zhxBare(word);
  for (const cand of zhxCandidates(word)) {
    const list = zhxIndex.get(cand);
    if (list) {
      // A match reached only by removing a single leading clitic letter (Arabic و/ف/ب/ك/ل,
      // Hebrew single-letter proclitics) is unreliable — it can land on an unrelated word
      // (كتبت→تبت "Tibet"). Flag it so the UI shows the result as uncertain rather than
      // confidently wrong. Multi-letter prefix strips (ال, וה) stay trusted.
      const risky = cand !== bare && bare.endsWith(cand) && bare.length - cand.length === 1;
      return { matched: cand, list, risky };
    }
  }
  return null;
}

function zhxTokenize(text) {
  const tokens = [];
  let last = 0;
  for (const m of text.matchAll(ZHX_WORD_RUN)) {
    if (m.index > last) tokens.push({ w: text.slice(last, m.index), p: null, han: false });
    const run = m[0];
    tokens.push({ w: run, p: null, han: true, h: 0 });
    last = m.index + run.length;
  }
  if (last < text.length) tokens.push({ w: text.slice(last), p: null, han: false });
  return tokens;
}

async function zhxHandle(msg) {
  await zhxEnsureDict();
  if (msg.type === 'lookup') {
    const hit = zhxLookupWord(msg.word);
    if (!hit) {
      return { found: false, word: msg.word, entries: [], chars: [] };
    }
    const list = zhxRankList(hit.list);
    return {
      found: true,
      word: msg.word,
      base: hit.matched !== msg.word && hit.matched !== msg.word.toLowerCase() ? hit.matched : undefined,
      tentative: !!hit.risky,
      hsk: 0,
      entries: [{ s: list[0].w, t: list[0].w, p: list[0].x || zhxTranslit(list[0].w), defs: list.map((e) => e.g).slice(0, 8) }],
      chars: [],
    };
  }
  if (msg.type === 'segmentBatch') {
    return msg.texts.map(zhxTokenize);
  }
  if (msg.type === 'examples') {
    zhxSentPromise ??= fetch(chrome.runtime.getURL('dict/fr/sentences.json'))
      .then((r) => r.json())
      .catch(() => ({ s: [], idx: {} }));
    const bank = await zhxSentPromise;
    const ids = bank.idx[msg.word] ?? bank.idx[msg.word.toLowerCase?.() ?? msg.word] ?? [];
    return ids.slice(0, msg.limit ?? 2).map((id) => {
      const [native, eng] = bank.s[id];
      return { tokens: zhxTokenize(native), eng };
    });
  }
  throw new Error('Unknown message type: ' + msg.type);
}

self.LENS.register("fr", { handle: zhxHandle });
})();

// ===== de (extension-de) =====
(function () {
'use strict';

const ZHX_WORD_RUN = /[A-Za-zÀ-ÖØ-öø-ÿäöüßÄÖÜ'\u2019-]+/g;
function zhxBare(w) { return w; }
function zhxTranslit() { return ''; }

function zhxCandidates(word) {
  const norm = word.replace(/[\u2018\u2019]/g, "'").replace(/[\u201C\u201D]/g, '"');
  const out = [norm];
  if (norm !== word) out.push(word);
  const lower = norm.toLowerCase();
  if (lower !== norm) out.push(lower);
  const strip = lower.replace(/^['"«»¿¡(]+|['"«»¿¡?!.,;:)]+$/g, '');
  if (strip && strip !== lower) out.push(strip);
  if (strip) out.push(strip[0].toUpperCase() + strip.slice(1));
  return [...new Set(out)];
}

let zhxIndex = null;
let zhxDictPromise = null;
let zhxSentPromise = null;

function zhxEnsureDict() {
  zhxDictPromise ??= (async () => {
    const rows = await (await fetch(chrome.runtime.getURL('dict/de/dict.json'))).json();
    zhxIndex = new Map();
    const add = (key, entry) => {
      if (!key) return;
      const list = zhxIndex.get(key);
      if (list) { if (list.length < 8) list.push(entry); } else zhxIndex.set(key, [entry]);
    };
    for (const [w, extra, gloss] of rows) {
      const entry = { w, x: extra, g: gloss };
      add(w, entry); const lower = w.toLowerCase(); if (lower !== w) add(lower, entry);
    }
  })();
  return zhxDictPromise;
}

// A gloss that is only a grammatical pointer ("(verb) inflection of estar") with no
// real definition. These should rank below entries that actually define the word.
const ZHX_POINTER_RE = /^(\([^)]*\)\s*)?(inflection|plural|singular|feminine|masculine|neuter|comparative|superlative|diminutive|augmentative|past participle|present participle|gerund|infinitive|conjugation|imperative|subjunctive|indicative|preterite|first-person|second-person|third-person|nominative|genitive|dative|accusative|vocative|construct|dual|alternative)\b[^;]*\bof\b/i;
function zhxRankList(list) {
  return [...list].sort((a, b) => (ZHX_POINTER_RE.test(a.g) ? 1 : 0) - (ZHX_POINTER_RE.test(b.g) ? 1 : 0));
}

function zhxLookupWord(word) {
  const bare = zhxBare(word);
  for (const cand of zhxCandidates(word)) {
    const list = zhxIndex.get(cand);
    if (list) {
      // A match reached only by removing a single leading clitic letter (Arabic و/ف/ب/ك/ل,
      // Hebrew single-letter proclitics) is unreliable — it can land on an unrelated word
      // (كتبت→تبت "Tibet"). Flag it so the UI shows the result as uncertain rather than
      // confidently wrong. Multi-letter prefix strips (ال, וה) stay trusted.
      const risky = cand !== bare && bare.endsWith(cand) && bare.length - cand.length === 1;
      return { matched: cand, list, risky };
    }
  }
  return null;
}

function zhxTokenize(text) {
  const tokens = [];
  let last = 0;
  for (const m of text.matchAll(ZHX_WORD_RUN)) {
    if (m.index > last) tokens.push({ w: text.slice(last, m.index), p: null, han: false });
    const run = m[0];
    tokens.push({ w: run, p: null, han: true, h: 0 });
    last = m.index + run.length;
  }
  if (last < text.length) tokens.push({ w: text.slice(last), p: null, han: false });
  return tokens;
}

async function zhxHandle(msg) {
  await zhxEnsureDict();
  if (msg.type === 'lookup') {
    const hit = zhxLookupWord(msg.word);
    if (!hit) {
      return { found: false, word: msg.word, entries: [], chars: [] };
    }
    const list = zhxRankList(hit.list);
    return {
      found: true,
      word: msg.word,
      base: hit.matched !== msg.word && hit.matched !== msg.word.toLowerCase() ? hit.matched : undefined,
      tentative: !!hit.risky,
      hsk: 0,
      entries: [{ s: list[0].w, t: list[0].w, p: list[0].x || zhxTranslit(list[0].w), defs: list.map((e) => e.g).slice(0, 8) }],
      chars: [],
    };
  }
  if (msg.type === 'segmentBatch') {
    return msg.texts.map(zhxTokenize);
  }
  if (msg.type === 'examples') {
    zhxSentPromise ??= fetch(chrome.runtime.getURL('dict/de/sentences.json'))
      .then((r) => r.json())
      .catch(() => ({ s: [], idx: {} }));
    const bank = await zhxSentPromise;
    const ids = bank.idx[msg.word] ?? bank.idx[msg.word.toLowerCase?.() ?? msg.word] ?? [];
    return ids.slice(0, msg.limit ?? 2).map((id) => {
      const [native, eng] = bank.s[id];
      return { tokens: zhxTokenize(native), eng };
    });
  }
  throw new Error('Unknown message type: ' + msg.type);
}

self.LENS.register("de", { handle: zhxHandle });
})();

// ===== es (extension-es) =====
(function () {
'use strict';

const ZHX_WORD_RUN = /[A-Za-zÀ-ÖØ-öø-ÿñÑáéíóúü'\u2019-]+/g;
function zhxBare(w) { return w; }
function zhxTranslit() { return ''; }

function zhxCandidates(word) {
  const norm = word.replace(/[\u2018\u2019]/g, "'").replace(/[\u201C\u201D]/g, '"');
  const out = [norm];
  if (norm !== word) out.push(word);
  const lower = norm.toLowerCase();
  if (lower !== norm) out.push(lower);
  const strip = lower.replace(/^['"«»¿¡(]+|['"«»¿¡?!.,;:)]+$/g, '');
  if (strip && strip !== lower) out.push(strip);
  
  return [...new Set(out)];
}

let zhxIndex = null;
let zhxDictPromise = null;
let zhxSentPromise = null;

function zhxEnsureDict() {
  zhxDictPromise ??= (async () => {
    const rows = await (await fetch(chrome.runtime.getURL('dict/es/dict.json'))).json();
    zhxIndex = new Map();
    const add = (key, entry) => {
      if (!key) return;
      const list = zhxIndex.get(key);
      if (list) { if (list.length < 8) list.push(entry); } else zhxIndex.set(key, [entry]);
    };
    for (const [w, extra, gloss] of rows) {
      const entry = { w, x: extra, g: gloss };
      add(w, entry); const lower = w.toLowerCase(); if (lower !== w) add(lower, entry);
    }
  })();
  return zhxDictPromise;
}

// A gloss that is only a grammatical pointer ("(verb) inflection of estar") with no
// real definition. These should rank below entries that actually define the word.
const ZHX_POINTER_RE = /^(\([^)]*\)\s*)?(inflection|plural|singular|feminine|masculine|neuter|comparative|superlative|diminutive|augmentative|past participle|present participle|gerund|infinitive|conjugation|imperative|subjunctive|indicative|preterite|first-person|second-person|third-person|nominative|genitive|dative|accusative|vocative|construct|dual|alternative)\b[^;]*\bof\b/i;
function zhxRankList(list) {
  return [...list].sort((a, b) => (ZHX_POINTER_RE.test(a.g) ? 1 : 0) - (ZHX_POINTER_RE.test(b.g) ? 1 : 0));
}

function zhxLookupWord(word) {
  const bare = zhxBare(word);
  for (const cand of zhxCandidates(word)) {
    const list = zhxIndex.get(cand);
    if (list) {
      // A match reached only by removing a single leading clitic letter (Arabic و/ف/ب/ك/ل,
      // Hebrew single-letter proclitics) is unreliable — it can land on an unrelated word
      // (كتبت→تبت "Tibet"). Flag it so the UI shows the result as uncertain rather than
      // confidently wrong. Multi-letter prefix strips (ال, וה) stay trusted.
      const risky = cand !== bare && bare.endsWith(cand) && bare.length - cand.length === 1;
      return { matched: cand, list, risky };
    }
  }
  return null;
}

function zhxTokenize(text) {
  const tokens = [];
  let last = 0;
  for (const m of text.matchAll(ZHX_WORD_RUN)) {
    if (m.index > last) tokens.push({ w: text.slice(last, m.index), p: null, han: false });
    const run = m[0];
    tokens.push({ w: run, p: null, han: true, h: 0 });
    last = m.index + run.length;
  }
  if (last < text.length) tokens.push({ w: text.slice(last), p: null, han: false });
  return tokens;
}

async function zhxHandle(msg) {
  await zhxEnsureDict();
  if (msg.type === 'lookup') {
    const hit = zhxLookupWord(msg.word);
    if (!hit) {
      return { found: false, word: msg.word, entries: [], chars: [] };
    }
    const list = zhxRankList(hit.list);
    return {
      found: true,
      word: msg.word,
      base: hit.matched !== msg.word && hit.matched !== msg.word.toLowerCase() ? hit.matched : undefined,
      tentative: !!hit.risky,
      hsk: 0,
      entries: [{ s: list[0].w, t: list[0].w, p: list[0].x || zhxTranslit(list[0].w), defs: list.map((e) => e.g).slice(0, 8) }],
      chars: [],
    };
  }
  if (msg.type === 'segmentBatch') {
    return msg.texts.map(zhxTokenize);
  }
  if (msg.type === 'examples') {
    zhxSentPromise ??= fetch(chrome.runtime.getURL('dict/es/sentences.json'))
      .then((r) => r.json())
      .catch(() => ({ s: [], idx: {} }));
    const bank = await zhxSentPromise;
    const ids = bank.idx[msg.word] ?? bank.idx[msg.word.toLowerCase?.() ?? msg.word] ?? [];
    return ids.slice(0, msg.limit ?? 2).map((id) => {
      const [native, eng] = bank.s[id];
      return { tokens: zhxTokenize(native), eng };
    });
  }
  throw new Error('Unknown message type: ' + msg.type);
}

self.LENS.register("es", { handle: zhxHandle });
})();

// ===== ms (extension-ms) =====
(function () {
'use strict';

const ZHX_WORD_RUN = /[A-Za-z][A-Za-z'-]*/g;
function zhxBare(w) { return w; }
function zhxTranslit() { return ''; }

const ZHX_SUFFIXES = ['lah', 'kah', 'tah', 'pun', 'ku', 'mu', 'nya', 'kan', 'an', 'i'];
function zhxStripPrefix(w) {
  const out = [];
  const push = (s) => { if (s && s.length >= 2) out.push(s); };
  for (const p of ['memper', 'diper', 'keber', 'ber', 'ter', 'per', 'pel', 'bel', 'tel', 'di', 'ke', 'se']) {
    if (w.startsWith(p) && w.length > p.length + 1) push(w.slice(p.length));
  }
  for (const base of ['me', 'pe']) {
    if (!w.startsWith(base)) continue;
    const rest = w.slice(base.length);
    push(rest);
    if (rest.startsWith('nge')) { push(rest.slice(3)); }
    if (rest.startsWith('ng')) { const r = rest.slice(2); push(r); push('k' + r); }
    else if (rest.startsWith('ny')) { const r = rest.slice(2); push(r); push('s' + r); }
    else if (rest.startsWith('n')) { const r = rest.slice(1); push(r); push('t' + r); push('d' + r); }
    else if (rest.startsWith('m')) { const r = rest.slice(1); push(r); push('p' + r); push('b' + r); push('f' + r); }
  }
  return out;
}
function zhxCandidates(word) {
  const lower = word.toLowerCase();
  const bases = new Set([lower]);
  const hy = lower.indexOf('-');
  if (hy > 0) { bases.add(lower.slice(0, hy)); bases.add(lower.slice(hy + 1).replace(/(an|nya)$/, '')); }
  const queue = [lower];
  let guard = 0;
  while (queue.length && guard++ < 40) {
    const b = queue.pop();
    for (const suf of ZHX_SUFFIXES) {
      if (b.endsWith(suf) && b.length > suf.length + 2) {
        const s = b.slice(0, -suf.length);
        if (!bases.has(s)) { bases.add(s); queue.push(s); }
      }
    }
  }
  const roots = new Set([lower]);
  // Recurse prefix stripping up to 3 layers so stacked prefixes peel
  // (diketahui: di- then ke- → tahu; memperkenalkan: memper- → kenal).
  for (const b of bases) {
    roots.add(b);
    let layer = [b];
    for (let depth = 0; depth < 3 && layer.length; depth++) {
      const next = [];
      for (const w of layer) for (const r of zhxStripPrefix(w)) if (!roots.has(r)) { roots.add(r); next.push(r); }
      layer = next;
    }
  }
  return [...roots];
}

let zhxIndex = null;
let zhxDictPromise = null;
let zhxSentPromise = null;

function zhxEnsureDict() {
  zhxDictPromise ??= (async () => {
    const rows = await (await fetch(chrome.runtime.getURL('dict/ms/dict.json'))).json();
    zhxIndex = new Map();
    const add = (key, entry) => {
      if (!key) return;
      const list = zhxIndex.get(key);
      if (list) { if (list.length < 8) list.push(entry); } else zhxIndex.set(key, [entry]);
    };
    for (const [w, extra, gloss] of rows) {
      const entry = { w, x: extra, g: gloss };
      add(w, entry); const lower = w.toLowerCase(); if (lower !== w) add(lower, entry);
    }
  })();
  return zhxDictPromise;
}

// A gloss that is only a grammatical pointer ("(verb) inflection of estar") with no
// real definition. These should rank below entries that actually define the word.
const ZHX_POINTER_RE = /^(\([^)]*\)\s*)?(inflection|plural|singular|feminine|masculine|neuter|comparative|superlative|diminutive|augmentative|past participle|present participle|gerund|infinitive|conjugation|imperative|subjunctive|indicative|preterite|first-person|second-person|third-person|nominative|genitive|dative|accusative|vocative|construct|dual|alternative)\b[^;]*\bof\b/i;
function zhxRankList(list) {
  return [...list].sort((a, b) => (ZHX_POINTER_RE.test(a.g) ? 1 : 0) - (ZHX_POINTER_RE.test(b.g) ? 1 : 0));
}

function zhxLookupWord(word) {
  const bare = zhxBare(word);
  for (const cand of zhxCandidates(word)) {
    const list = zhxIndex.get(cand);
    if (list) {
      // A match reached only by removing a single leading clitic letter (Arabic و/ف/ب/ك/ل,
      // Hebrew single-letter proclitics) is unreliable — it can land on an unrelated word
      // (كتبت→تبت "Tibet"). Flag it so the UI shows the result as uncertain rather than
      // confidently wrong. Multi-letter prefix strips (ال, וה) stay trusted.
      const risky = cand !== bare && bare.endsWith(cand) && bare.length - cand.length === 1;
      return { matched: cand, list, risky };
    }
  }
  return null;
}

// Reduplication note (Malay 词-doubling carries meaning): kanak-kanak = plural,
// sayur-sayuran = variety, tolong-menolong = reciprocal.
function zhxRedup(word) {
  const hy = word.indexOf('-');
  if (hy <= 0) return undefined;
  const a = word.slice(0, hy).toLowerCase();
  const b = word.slice(hy + 1).toLowerCase();
  if (a === b) return 'reduplication — plural or repetition of "' + a + '"';
  if (b === a + 'an' || b === a + 'kan') return 'reduplication — variety/collective of "' + a + '"';
  if (/^(me|men|mem|meng|meny)/.test(b) && b.length > 3) return 'reduplication — reciprocal (doing "' + a + '" to one another)';
  return undefined;
}

function zhxTokenize(text) {
  const tokens = [];
  let last = 0;
  for (const m of text.matchAll(ZHX_WORD_RUN)) {
    if (m.index > last) tokens.push({ w: text.slice(last, m.index), p: null, han: false });
    const run = m[0];
    tokens.push({ w: run, p: null, han: true, h: 0 });
    last = m.index + run.length;
  }
  if (last < text.length) tokens.push({ w: text.slice(last), p: null, han: false });
  return tokens;
}

async function zhxHandle(msg) {
  await zhxEnsureDict();
  if (msg.type === 'lookup') {
    const hit = zhxLookupWord(msg.word);
    if (!hit) {
      return { found: false, word: msg.word, entries: [], chars: [] };
    }
    const list = zhxRankList(hit.list);
    return {
      found: true,
      word: msg.word,
      base: hit.matched !== msg.word && hit.matched !== msg.word.toLowerCase() ? hit.matched : undefined,
      tentative: !!hit.risky,
      redup: zhxRedup(msg.word),
      hsk: 0,
      entries: [{ s: list[0].w, t: list[0].w, p: list[0].x || zhxTranslit(list[0].w), defs: list.map((e) => e.g).slice(0, 8) }],
      chars: [],
    };
  }
  if (msg.type === 'segmentBatch') {
    return msg.texts.map(zhxTokenize);
  }
  if (msg.type === 'examples') {
    zhxSentPromise ??= fetch(chrome.runtime.getURL('dict/ms/sentences.json'))
      .then((r) => r.json())
      .catch(() => ({ s: [], idx: {} }));
    const bank = await zhxSentPromise;
    const ids = bank.idx[msg.word] ?? bank.idx[msg.word.toLowerCase?.() ?? msg.word] ?? [];
    return ids.slice(0, msg.limit ?? 2).map((id) => {
      const [native, eng] = bank.s[id];
      return { tokens: zhxTokenize(native), eng };
    });
  }
  throw new Error('Unknown message type: ' + msg.type);
}

self.LENS.register("ms", { handle: zhxHandle });
})();
